### ISSUE TITLE
content-search sq example in documentation does not work

### ISSUE THREAD

**Issue by kenrestivo** [cldwalker/logseq-query#4]
I tried the example in your documentation, and got:

```
 lq sq '(content-search ?b "github.com/")'

node:internal/process/esm_loader:79
    internalBinding('errors').triggerUncaughtException(
                              ^
Cm [Error]: Unknown rule 'content-search in (content-search ?b "github.com/")
    at new Cm (file:///home/lken/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:183:149)
    at $APP.Bo.j (file:///home/lken/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:1508:319)
    at ht (file:///home/lken/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:340:399)
    at file:///home/lken/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:624:361
    at O (file:///home/lken/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:313:469)
    at file:///home/lken/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:553:96
    at O (file:///home/lken/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:313:469)
    at file:///home/lken/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:553:234
    at O (file:///home/lken/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:313:469)
    at file:///home/lken/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:416:349 {
  data: {
    K: null,
    O: 6,
    H: [
      {
        Fc: null,
        name: 'type',
        S: 'type',
        Rc: 1174270348,
        J: 2153775105,
        N: 4096
      },
      {
        Fc: 'sci',
        name: 'error',
        S: 'sci/error',
        Rc: -979082803,
        J: 2153775105,
        N: 4096
      },
      {
        Fc: null,
        name: 'line',
        S: 'line',
        Rc: 212345235,
        J: 2153775105,
        N: 4096
      },
      145,
      {
        Fc: null,
        name: 'column',
        S: 'column',
        Rc: 2078222095,
        J: 2153775105,
        N: 4096
      },
      13,
      {
        Fc: null,
        name: 'message',
        S: 'message',
        Rc: -406056002,
        J: 2153775105,
        N: 4096
      },
      `Unknown rule 'content-search in (content-search ?b "github.com/")`,
      {
        Fc: 'sci.impl',
        name: 'callstack',
        S: 'sci.impl/callstack',
        Rc: -1621010557,
        J: 2153775105,
        N: 4096
      },
      gi {
        state: {
          K: null,
          first: {
            K: null,
            O: 5,
            H: [Array],
            D: null,
            J: 16647951,
            N: 139268
          },
          Tb: {
            K: null,
            first: [Object],
            Tb: [Object],
            count: 9,
            D: null,
            J: 65937646,
            N: 8192
          },
          count: 10,
          D: null,
          J: 65937646,
          N: 8192
        },
        J: 32768,
        N: 0
      },
      {
        Fc: null,
        name: 'file',
        S: 'file',
        Rc: -1269645878,
        J: 2153775105,
        N: 4096
      },
      '/home/lken/node_modules/logseq-query/src/cldwalker/logseq_query/datascript.cljs'
    ],
    D: null,
    J: 16647951,
    N: 139268
  },
  ng: Cm [Error]: Unknown rule 'content-search in (content-search ?b "github.com/")
      at new Cm (file:///home/lken/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:183:149)
      at $APP.Bo.j (file:///home/lken/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:1508:319)
      at $APP.Bo.h (file:///home/lken/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:1508:273)
      at o3 (file:///home/lken/node_modules/@logseq/nbb-logseq/lib/nbb_datascript.js:245:381)
      at A3 (file:///home/lken/node_modules/@logseq/nbb-logseq/lib/nbb_datascript.js:705:132)
      at $APP.f.Ra (file:///home/lken/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:1222:384)
      at $APP.Af.j (file:///home/lken/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:1002:253)
      at tpa (file:///home/lken/node_modules/@logseq/nbb-logseq/lib/nbb_datascript.js:267:301)
      at J4.l (file:///home/lken/node_modules/@logseq/nbb-logseq/lib/nbb_datascript.js:708:400)
      at J4.G (file:///home/lken/node_modules/@logseq/nbb-logseq/lib/nbb_datascript.js:709:175) {
    data: {
      K: null,
      O: 2,
      H: [
        {
          Fc: null,
          name: 'error',
          S: 'error',
          Rc: -978969032,
          J: 2153775105,
          N: 4096
        },
        {
          Fc: 'query',
          name: 'where',
          S: 'query/where',
          Rc: -1935159429,
          J: 2153775105,
          N: 4096
        },
        {
          Fc: null,
          name: 'form',
          S: 'form',
          Rc: -1624062471,
          J: 2153775105,
          N: 4096
        },
        {
          K: null,
          first: {
            Fc: null,
            name: 'content-search',
            Gc: 'content-search',
            Rc: null,
            xd: null,
            J: 2154168321,
            N: 4096
          },
          Tb: {
            K: null,
            first: [Object],
            Tb: [Object],
            count: 2,
            D: null,
            J: 65937646,
            N: 8192
          },
          count: 3,
          D: null,
          J: 65937646,
          N: 8192
        }
      ],
      D: null,
      J: 16647951,
      N: 139268
    },
    ng: null,
    description: undefined,
    number: undefined,
    fileName: undefined,
    lineNumber: undefined,
    columnNumber: undefined
  },
  description: undefined,
  number: undefined,
  fileName: undefined,
  lineNumber: undefined,
  columnNumber: undefined
}

Node.js v19.4.0
```

q works, but sq appears not to.

`lq queries` shows the content-search query.

**Comment by cldwalker** [comment]
Thanks for the report. All the sq examples should say `block-content`. Fixing soon
