### ISSUE TITLE
Exception when adding query from example docs

### ISSUE THREAD

**Issue by WesHoward** [cldwalker/logseq-query#5]
Unable to add queries

When I add any query to queries.edn I am getting exceptions. When addin the example directly from the readme and testing that I get the following error:

(base) whoward@C02FN196ML87 ~ % lq queries

node:internal/process/esm_loader:46
      internalBinding('errors').triggerUncaughtException(
                                ^
Cm [Error]: :cldwalker/github-tasks is not ISeqable
    at new Cm (file:///usr/local/lib/node_modules/logseq-query/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:183:149)
    at $APP.Bo.j (file:///usr/local/lib/node_modules/logseq-query/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:1508:319)
    at ht (file:///usr/local/lib/node_modules/logseq-query/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:340:399)
    at file:///usr/local/lib/node_modules/logseq-query/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:623:412
    at O (file:///usr/local/lib/node_modules/logseq-query/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:313:469)
    at file:///usr/local/lib/node_modules/logseq-query/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:415:132
    at file:///usr/local/lib/node_modules/logseq-query/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:622:151
    at O (file:///usr/local/lib/node_modules/logseq-query/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:313:469)
    at file:///usr/local/lib/node_modules/logseq-query/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:623:286
    at O (file:///usr/local/lib/node_modules/logseq-query/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:313:469) {
  data: {
    K: null,
    O: 6,
    H: [
      {
        Fc: null,
        name: 'type',
        S: 'type',
        Rc: 1174270348,
        J: 2153775105,
        N: 4096
      },
      {
        Fc: 'sci',
        name: 'error',
        S: 'sci/error',
        Rc: -979082803,
        J: 2153775105,
        N: 4096
      },
      {
        Fc: null,
        name: 'line',
        S: 'line',
        Rc: 212345235,
        J: 2153775105,
        N: 4096
      },
      77,
      {
        Fc: null,
        name: 'column',
        S: 'column',
        Rc: 2078222095,
        J: 2153775105,
        N: 4096
      },
      3,
      {
        Fc: null,
        name: 'message',
        S: 'message',
        Rc: -406056002,
        J: 2153775105,
        N: 4096
      },
      ':cldwalker/github-tasks is not ISeqable',
      {
        Fc: 'sci.impl',
        name: 'callstack',
        S: 'sci.impl/callstack',
        Rc: -1621010557,
        J: 2153775105,
        N: 4096
      },
      gi {
        state: {
          K: null,
          first: {
            K: null,
            O: 5,
            H: [Array],
            D: null,
            J: 16647951,
            N: 139268
          },
          Tb: {
            K: null,
            first: [Object],
            Tb: [Object],
            count: 6,
            D: null,
            J: 65937646,
            N: 8192
          },
          count: 7,
          D: null,
          J: 65937646,
          N: 8192
        },
        J: 32768,
        N: 0
      },
      {
        Fc: null,
        name: 'file',
        S: 'file',
        Rc: -1269645878,
        J: 2153775105,
        N: 4096
      },
      '/usr/local/lib/node_modules/logseq-query/src/cldwalker/logseq_query/util.cljs'
    ],
    D: null,
    J: 16647951,
    N: 139268
  },
  ng: Error: :cldwalker/github-tasks is not ISeqable
      at $APP.v (file:///usr/local/lib/node_modules/logseq-query/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:68:305)
      at $APP.f.ca (file:///usr/local/lib/node_modules/logseq-query/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:1277:185)
      at $APP.Vb (file:///usr/local/lib/node_modules/logseq-query/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:31:50)
      at $APP.Lg.h (file:///usr/local/lib/node_modules/logseq-query/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:970:424)
      at file:///usr/local/lib/node_modules/logseq-query/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:1366:262
      at ne (file:///usr/local/lib/node_modules/logseq-query/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:73:430)
      at $APP.f.Qa (file:///usr/local/lib/node_modules/logseq-query/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:964:154)
      at $APP.Af.h (file:///usr/local/lib/node_modules/logseq-query/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:1002:72)
      at $APP.ro.l (file:///usr/local/lib/node_modules/logseq-query/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:1366:231)
      at ro (file:///usr/local/lib/node_modules/logseq-query/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:1366:116),
  description: undefined,
  number: undefined,
  fileName: undefined,
  lineNumber: undefined,
  columnNumber: undefined
}

Node.js v20.5.1

**Comment by lbraglia** [comment]
for me is the same

**Comment by jibe-b** [comment]
+1

**Comment by zh3036** [comment]
add {} outside of the query, it is not a single query, but a list of queries
